### ISSUE TITLE
Cannot download Oodle DLL

### ISSUE THREAD

**Issue by Im2rnado** [Sprayxe/unreal.js#5]
**Describe the bug**
Downloading Oodle DLL using `Oodle.downloadDLL()` returns status code 403
```
(node:9628) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (C:\Users\Administrator\Desktop\Shadow-Bot\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Administrator\Desktop\Shadow-Bot\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Administrator\Desktop\Shadow-Bot\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/65093857/123558524-017dfe80-d797-11eb-8203-e3c240781cb1.png)

**Additional information**
1. Unreal.JS - v1.0.6
2. Fortnite - v17.1

**Comment by Sprayxe** [comment]
Is this the full stack trace?

**Comment by alextusinean** [comment]
This is most likely an issue on your end as I can't reproduce it. Can you try accessing [https://origin.warframe.com/](https://origin.warframe.com/)? You should get a 404 Not Found.

**Comment by Im2rnado** [comment]
> This is most likely an issue on your end as I can't reproduce it. Can you try accessing https://origin.warframe.com/? You should get a 404 Not Found.

Yep 
![image](https://user-images.githubusercontent.com/65093857/123698132-107bb400-d85e-11eb-9bd0-47a758ac6ca7.png)

**Comment by Im2rnado** [comment]
> Is this the full stack trace?

Yes

**Comment by Sprayxe** [comment]
Unable to reproduce the error
